### ISSUE TITLE
DocTypeMeta issue

### ISSUE THREAD

**Issue by tiagoarasilva** [sabricot/django-elasticsearch-dsl#116] opened 2018-07-05 09:43 UTC
Hi, with the new version of elasticsearch >= 6.2 the DocTypeMeta was removed/renamed to `DocumentMeta`. I've tried to open a PR or even clone it but for some reason I couldn't.

Thanks,
Tiago

**Comment by domface** [comment] 2018-07-05 12:01
+1

**Comment by jaddison** [comment] 2018-07-25 17:48
Duplicate of #115.

**Comment by alaminopu** [comment] 2019-08-24 23:09
@safwanrahman This issue has been discussed in #115 and resolved in #136. It should be closed in favor of #136

**Comment by tiagoarasilva** [comment] 2019-09-16 13:24
If it was fixed, then the issue should be closed.

**Closed** 2019-09-16 13:24 UTC
