### ISSUE TITLE
Error after updating to elasticsearch 7.1.0

### ISSUE THREAD

**Issue by fly1ngDream** [sabricot/django-elasticsearch-dsl#174] opened 2019-05-26 15:17 UTC
documents.py :
```
from django_elasticsearch_dsl import DocType, Index
from .models import File


textfile = Index('textfiles')

@textfile.doc_type
class FileDocument(DocType):
    class Meta:
        model = File

        fields = (
            'name',
            'description',
        )
```
after running ./manage.py search index --create/--rebuild :
```
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [doc : {properties={name={type=text}, description={type=text}}}]')

```

**Comment by barseghyanartur** [comment] 2019-05-30 22:04
@fly1ngDream:

Duplicate of #170

**Closed** 2019-06-03 01:03 UTC
